import type { NewCategory } from "$lib/schema";

/**
 * Default popular categories that users can optionally seed into their budget
 * Organized by category type with common subcategories
 */
export const defaultCategories: Omit<NewCategory, 'id' | 'dateCreated' | 'createdAt' | 'updatedAt' | 'deletedAt'>[] = [
  // ============ INCOME CATEGORIES ============
  {
    name: "Income",
    slug: "income",
    categoryType: "income",
    categoryIcon: "dollar-sign",
    categoryColor: "#10b981",
    isActive: true,
    displayOrder: 0,
    isTaxDeductible: false,
    incomeReliability: "guaranteed",
  },
  {
    name: "Salary",
    slug: "salary",
    categoryType: "income",
    categoryIcon: "briefcase",
    categoryColor: "#10b981",
    isActive: true,
    displayOrder: 1,
    isTaxDeductible: false,
    incomeReliability: "guaranteed",
  },
  {
    name: "Freelance",
    slug: "freelance",
    categoryType: "income",
    categoryIcon: "laptop",
    categoryColor: "#10b981",
    isActive: true,
    displayOrder: 2,
    isTaxDeductible: false,
    incomeReliability: "variable",
  },
  {
    name: "Investments",
    slug: "investments-income",
    categoryType: "income",
    categoryIcon: "trending-up",
    categoryColor: "#10b981",
    isActive: true,
    displayOrder: 3,
    isTaxDeductible: false,
    incomeReliability: "variable",
  },
  {
    name: "Bonus",
    slug: "bonus",
    categoryType: "income",
    categoryIcon: "gift",
    categoryColor: "#10b981",
    isActive: true,
    displayOrder: 4,
    isTaxDeductible: false,
    incomeReliability: "variable",
  },

  // ============ ESSENTIAL EXPENSES ============
  {
    name: "Housing",
    slug: "housing",
    categoryType: "expense",
    categoryIcon: "home",
    categoryColor: "#ef4444",
    isActive: true,
    displayOrder: 100,
    spendingPriority: "essential",
  },
  {
    name: "Rent/Mortgage",
    slug: "rent-mortgage",
    categoryType: "expense",
    categoryIcon: "key",
    categoryColor: "#ef4444",
    isActive: true,
    displayOrder: 101,
    spendingPriority: "essential",
    isTaxDeductible: false,
  },
  {
    name: "Utilities",
    slug: "utilities",
    categoryType: "expense",
    categoryIcon: "zap",
    categoryColor: "#f59e0b",
    isActive: true,
    displayOrder: 102,
    spendingPriority: "essential",
  },
  {
    name: "Internet & Phone",
    slug: "internet-phone",
    categoryType: "expense",
    categoryIcon: "wifi",
    categoryColor: "#f59e0b",
    isActive: true,
    displayOrder: 103,
    spendingPriority: "essential",
  },
  {
    name: "Groceries",
    slug: "groceries",
    categoryType: "expense",
    categoryIcon: "shopping-cart",
    categoryColor: "#10b981",
    isActive: true,
    displayOrder: 104,
    spendingPriority: "essential",
  },

  // ============ TRANSPORTATION ============
  {
    name: "Transportation",
    slug: "transportation",
    categoryType: "expense",
    categoryIcon: "car",
    categoryColor: "#3b82f6",
    isActive: true,
    displayOrder: 200,
    spendingPriority: "important",
  },
  {
    name: "Gas/Fuel",
    slug: "gas-fuel",
    categoryType: "expense",
    categoryIcon: "fuel",
    categoryColor: "#3b82f6",
    isActive: true,
    displayOrder: 201,
    spendingPriority: "important",
  },
  {
    name: "Car Payment",
    slug: "car-payment",
    categoryType: "expense",
    categoryIcon: "credit-card",
    categoryColor: "#3b82f6",
    isActive: true,
    displayOrder: 202,
    spendingPriority: "important",
  },
  {
    name: "Car Insurance",
    slug: "car-insurance",
    categoryType: "expense",
    categoryIcon: "shield",
    categoryColor: "#3b82f6",
    isActive: true,
    displayOrder: 203,
    spendingPriority: "important",
  },
  {
    name: "Car Maintenance",
    slug: "car-maintenance",
    categoryType: "expense",
    categoryIcon: "wrench",
    categoryColor: "#3b82f6",
    isActive: true,
    displayOrder: 204,
    spendingPriority: "important",
  },
  {
    name: "Public Transit",
    slug: "public-transit",
    categoryType: "expense",
    categoryIcon: "train",
    categoryColor: "#3b82f6",
    isActive: true,
    displayOrder: 205,
    spendingPriority: "important",
  },

  // ============ HEALTHCARE ============
  {
    name: "Healthcare",
    slug: "healthcare",
    categoryType: "expense",
    categoryIcon: "heart",
    categoryColor: "#ec4899",
    isActive: true,
    displayOrder: 300,
    spendingPriority: "important",
  },
  {
    name: "Health Insurance",
    slug: "health-insurance",
    categoryType: "expense",
    categoryIcon: "shield",
    categoryColor: "#ec4899",
    isActive: true,
    displayOrder: 301,
    spendingPriority: "important",
    isTaxDeductible: true,
    taxCategory: "medical_expenses",
  },
  {
    name: "Medical Expenses",
    slug: "medical-expenses",
    categoryType: "expense",
    categoryIcon: "activity",
    categoryColor: "#ec4899",
    isActive: true,
    displayOrder: 302,
    spendingPriority: "important",
    isTaxDeductible: true,
    taxCategory: "medical_expenses",
  },
  {
    name: "Prescriptions",
    slug: "prescriptions",
    categoryType: "expense",
    categoryIcon: "pill",
    categoryColor: "#ec4899",
    isActive: true,
    displayOrder: 303,
    spendingPriority: "important",
    isTaxDeductible: true,
    taxCategory: "medical_expenses",
  },
  {
    name: "Dental",
    slug: "dental",
    categoryType: "expense",
    categoryIcon: "smile",
    categoryColor: "#ec4899",
    isActive: true,
    displayOrder: 304,
    spendingPriority: "important",
    isTaxDeductible: true,
    taxCategory: "medical_expenses",
  },

  // ============ FOOD & DINING ============
  {
    name: "Food & Dining",
    slug: "food-dining",
    categoryType: "expense",
    categoryIcon: "utensils",
    categoryColor: "#f97316",
    isActive: true,
    displayOrder: 400,
    spendingPriority: "discretionary",
  },
  {
    name: "Restaurants",
    slug: "restaurants",
    categoryType: "expense",
    categoryIcon: "coffee",
    categoryColor: "#f97316",
    isActive: true,
    displayOrder: 401,
    spendingPriority: "discretionary",
  },
  {
    name: "Fast Food",
    slug: "fast-food",
    categoryType: "expense",
    categoryIcon: "pizza",
    categoryColor: "#f97316",
    isActive: true,
    displayOrder: 402,
    spendingPriority: "discretionary",
  },
  {
    name: "Coffee Shops",
    slug: "coffee-shops",
    categoryType: "expense",
    categoryIcon: "coffee",
    categoryColor: "#f97316",
    isActive: true,
    displayOrder: 403,
    spendingPriority: "discretionary",
  },

  // ============ ENTERTAINMENT ============
  {
    name: "Entertainment",
    slug: "entertainment",
    categoryType: "expense",
    categoryIcon: "film",
    categoryColor: "#8b5cf6",
    isActive: true,
    displayOrder: 500,
    spendingPriority: "discretionary",
  },
  {
    name: "Streaming Services",
    slug: "streaming-services",
    categoryType: "expense",
    categoryIcon: "tv",
    categoryColor: "#8b5cf6",
    isActive: true,
    displayOrder: 501,
    spendingPriority: "discretionary",
  },
  {
    name: "Movies & Shows",
    slug: "movies-shows",
    categoryType: "expense",
    categoryIcon: "film",
    categoryColor: "#8b5cf6",
    isActive: true,
    displayOrder: 502,
    spendingPriority: "discretionary",
  },
  {
    name: "Hobbies",
    slug: "hobbies",
    categoryType: "expense",
    categoryIcon: "gamepad",
    categoryColor: "#8b5cf6",
    isActive: true,
    displayOrder: 503,
    spendingPriority: "discretionary",
  },
  {
    name: "Sports & Recreation",
    slug: "sports-recreation",
    categoryType: "expense",
    categoryIcon: "target",
    categoryColor: "#8b5cf6",
    isActive: true,
    displayOrder: 504,
    spendingPriority: "discretionary",
  },

  // ============ SHOPPING ============
  {
    name: "Shopping",
    slug: "shopping",
    categoryType: "expense",
    categoryIcon: "shopping-bag",
    categoryColor: "#06b6d4",
    isActive: true,
    displayOrder: 600,
    spendingPriority: "discretionary",
  },
  {
    name: "Clothing",
    slug: "clothing",
    categoryType: "expense",
    categoryIcon: "shirt",
    categoryColor: "#06b6d4",
    isActive: true,
    displayOrder: 601,
    spendingPriority: "discretionary",
  },
  {
    name: "Electronics",
    slug: "electronics",
    categoryType: "expense",
    categoryIcon: "smartphone",
    categoryColor: "#06b6d4",
    isActive: true,
    displayOrder: 602,
    spendingPriority: "discretionary",
  },
  {
    name: "Home Goods",
    slug: "home-goods",
    categoryType: "expense",
    categoryIcon: "couch",
    categoryColor: "#06b6d4",
    isActive: true,
    displayOrder: 603,
    spendingPriority: "discretionary",
  },

  // ============ PERSONAL CARE ============
  {
    name: "Personal Care",
    slug: "personal-care",
    categoryType: "expense",
    categoryIcon: "user",
    categoryColor: "#a855f7",
    isActive: true,
    displayOrder: 700,
    spendingPriority: "discretionary",
  },
  {
    name: "Haircuts & Salon",
    slug: "haircuts-salon",
    categoryType: "expense",
    categoryIcon: "scissors",
    categoryColor: "#a855f7",
    isActive: true,
    displayOrder: 701,
    spendingPriority: "discretionary",
  },
  {
    name: "Gym & Fitness",
    slug: "gym-fitness",
    categoryType: "expense",
    categoryIcon: "dumbbell",
    categoryColor: "#a855f7",
    isActive: true,
    displayOrder: 702,
    spendingPriority: "discretionary",
  },

  // ============ EDUCATION ============
  {
    name: "Education",
    slug: "education",
    categoryType: "expense",
    categoryIcon: "book",
    categoryColor: "#14b8a6",
    isActive: true,
    displayOrder: 800,
    spendingPriority: "important",
  },
  {
    name: "Tuition",
    slug: "tuition",
    categoryType: "expense",
    categoryIcon: "graduation-cap",
    categoryColor: "#14b8a6",
    isActive: true,
    displayOrder: 801,
    spendingPriority: "important",
    isTaxDeductible: true,
    taxCategory: "education",
  },
  {
    name: "Books & Supplies",
    slug: "books-supplies",
    categoryType: "expense",
    categoryIcon: "book-open",
    categoryColor: "#14b8a6",
    isActive: true,
    displayOrder: 802,
    spendingPriority: "important",
    isTaxDeductible: false,
  },
  {
    name: "Online Courses",
    slug: "online-courses",
    categoryType: "expense",
    categoryIcon: "monitor",
    categoryColor: "#14b8a6",
    isActive: true,
    displayOrder: 803,
    spendingPriority: "important",
  },

  // ============ INSURANCE ============
  {
    name: "Insurance",
    slug: "insurance",
    categoryType: "expense",
    categoryIcon: "shield",
    categoryColor: "#6366f1",
    isActive: true,
    displayOrder: 900,
    spendingPriority: "important",
  },
  {
    name: "Life Insurance",
    slug: "life-insurance",
    categoryType: "expense",
    categoryIcon: "heart-pulse",
    categoryColor: "#6366f1",
    isActive: true,
    displayOrder: 901,
    spendingPriority: "important",
  },
  {
    name: "Home Insurance",
    slug: "home-insurance",
    categoryType: "expense",
    categoryIcon: "home",
    categoryColor: "#6366f1",
    isActive: true,
    displayOrder: 902,
    spendingPriority: "important",
  },

  // ============ DEBT & LOANS ============
  {
    name: "Debt & Loans",
    slug: "debt-loans",
    categoryType: "expense",
    categoryIcon: "credit-card",
    categoryColor: "#dc2626",
    isActive: true,
    displayOrder: 1000,
    spendingPriority: "important",
  },
  {
    name: "Credit Card Payment",
    slug: "credit-card-payment",
    categoryType: "expense",
    categoryIcon: "credit-card",
    categoryColor: "#dc2626",
    isActive: true,
    displayOrder: 1001,
    spendingPriority: "important",
  },
  {
    name: "Student Loans",
    slug: "student-loans",
    categoryType: "expense",
    categoryIcon: "graduation-cap",
    categoryColor: "#dc2626",
    isActive: true,
    displayOrder: 1002,
    spendingPriority: "important",
  },
  {
    name: "Personal Loan",
    slug: "personal-loan",
    categoryType: "expense",
    categoryIcon: "dollar-sign",
    categoryColor: "#dc2626",
    isActive: true,
    displayOrder: 1003,
    spendingPriority: "important",
  },

  // ============ SAVINGS ============
  {
    name: "Emergency Fund",
    slug: "emergency-fund",
    categoryType: "savings",
    categoryIcon: "life-buoy",
    categoryColor: "#059669",
    isActive: true,
    displayOrder: 1100,
    spendingPriority: "essential",
  },
  {
    name: "Vacation Fund",
    slug: "vacation-fund",
    categoryType: "savings",
    categoryIcon: "plane",
    categoryColor: "#0891b2",
    isActive: true,
    displayOrder: 1101,
    spendingPriority: "discretionary",
  },
  {
    name: "Retirement",
    slug: "retirement",
    categoryType: "savings",
    categoryIcon: "piggy-bank",
    categoryColor: "#059669",
    isActive: true,
    displayOrder: 1102,
    spendingPriority: "important",
  },
  {
    name: "Home Down Payment",
    slug: "home-down-payment",
    categoryType: "savings",
    categoryIcon: "home",
    categoryColor: "#059669",
    isActive: true,
    displayOrder: 1103,
    spendingPriority: "important",
  },

  // ============ GIVING ============
  {
    name: "Giving",
    slug: "giving",
    categoryType: "expense",
    categoryIcon: "heart",
    categoryColor: "#f472b6",
    isActive: true,
    displayOrder: 1200,
    spendingPriority: "discretionary",
  },
  {
    name: "Charity",
    slug: "charity",
    categoryType: "expense",
    categoryIcon: "hand-heart",
    categoryColor: "#f472b6",
    isActive: true,
    displayOrder: 1201,
    spendingPriority: "discretionary",
    isTaxDeductible: true,
    taxCategory: "charitable_contributions",
  },
  {
    name: "Gifts",
    slug: "gifts",
    categoryType: "expense",
    categoryIcon: "gift",
    categoryColor: "#f472b6",
    isActive: true,
    displayOrder: 1202,
    spendingPriority: "discretionary",
  },

  // ============ PETS ============
  {
    name: "Pets",
    slug: "pets",
    categoryType: "expense",
    categoryIcon: "paw",
    categoryColor: "#fb923c",
    isActive: true,
    displayOrder: 1300,
    spendingPriority: "important",
  },
  {
    name: "Pet Food",
    slug: "pet-food",
    categoryType: "expense",
    categoryIcon: "bone",
    categoryColor: "#fb923c",
    isActive: true,
    displayOrder: 1301,
    spendingPriority: "important",
  },
  {
    name: "Veterinary",
    slug: "veterinary",
    categoryType: "expense",
    categoryIcon: "stethoscope",
    categoryColor: "#fb923c",
    isActive: true,
    displayOrder: 1302,
    spendingPriority: "important",
  },

  // ============ BUSINESS EXPENSES ============
  {
    name: "Business Expenses",
    slug: "business-expenses",
    categoryType: "expense",
    categoryIcon: "briefcase",
    categoryColor: "#0ea5e9",
    isActive: true,
    displayOrder: 1400,
    spendingPriority: "important",
  },
  {
    name: "Office Supplies",
    slug: "office-supplies",
    categoryType: "expense",
    categoryIcon: "printer",
    categoryColor: "#0ea5e9",
    isActive: true,
    displayOrder: 1401,
    spendingPriority: "important",
    isTaxDeductible: false,
    taxCategory: "business_expenses",
  },
  {
    name: "Software & Subscriptions",
    slug: "software-subscriptions",
    categoryType: "expense",
    categoryIcon: "laptop",
    categoryColor: "#0ea5e9",
    isActive: true,
    displayOrder: 1402,
    spendingPriority: "important",
    isTaxDeductible: false,
    taxCategory: "business_expenses",
  },

  // ============ MISCELLANEOUS ============
  {
    name: "Miscellaneous",
    slug: "miscellaneous",
    categoryType: "expense",
    categoryIcon: "package",
    categoryColor: "#64748b",
    isActive: true,
    displayOrder: 1500,
    spendingPriority: "discretionary",
  },
  {
    name: "Fees & Charges",
    slug: "fees-charges",
    categoryType: "expense",
    categoryIcon: "alert-circle",
    categoryColor: "#64748b",
    isActive: true,
    displayOrder: 1501,
    spendingPriority: "discretionary",
  },
  {
    name: "ATM Fees",
    slug: "atm-fees",
    categoryType: "expense",
    categoryIcon: "dollar-sign",
    categoryColor: "#64748b",
    isActive: true,
    displayOrder: 1502,
    spendingPriority: "discretionary",
  },

  // ============ TRANSFERS ============
  {
    name: "Transfer",
    slug: "transfer",
    categoryType: "transfer",
    categoryIcon: "repeat",
    categoryColor: "#64748b",
    isActive: true,
    displayOrder: 1600,
  },
];
