/**
 * Pure detection pipeline for auto-generated rooms and zones.
 *
 * The algorithm ingests the current wall/fence segments, groups them by
 * their hierarchy parent, looks for simple closed cycles, and emits one
 * "region" record per cycle. The reactive wrapper in `FloorPlanStore`
 * consumes the regions to create / update / delete room & zone nodes.
 *
 * Extracted from the store so the graph-traversal math is testable in
 * isolation — no reactive state, no `this`, no side effects. The store
 * owns the node map; this module owns the geometry/topology.
 */

import type { FloorPlanNode } from "$core/schema/home/home-floor-plan-nodes";

const AUTO_DETECT_ENDPOINT_TOLERANCE_RATIO = 0.3;
const AUTO_DETECT_MIN_AREA = 400;
const AUTO_DETECT_MIN_DIMENSION = 10;

export type AutoDetectBoundaryEdge = {
  id: string;
  nodeType: "wall" | "fence";
  parentId: string | null;
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  startKey: string;
  endKey: string;
};

export type AutoDetectedRegion = {
  parentId: string | null;
  parentKey: string;
  nodeType: "room" | "zone";
  signature: string;
  edgeIds: string[];
  minX: number;
  minY: number;
  width: number;
  height: number;
};

export type AutoDetectResult = {
  regions: AutoDetectedRegion[];
  /**
   * Parent keys whose wall graph had a vertex of degree > 2 (i.e. a wall
   * junction that branches). The store suppresses deletion of pre-existing
   * auto-detected nodes within these parents so partial wall moves don't
   * drop user-retained spaces on the floor.
   */
  blockedDeletionParentKeys: Set<string>;
  /** Parent keys that had any wall/fence edges processed. */
  processedParentKeys: Set<string>;
};

export function toParentGroupKey(parentId: string | null): string {
  return parentId ?? "__root__";
}

export function toBoundaryPointKey(x: number, y: number, tolerance: number): string {
  const qx = Math.round(x / tolerance);
  const qy = Math.round(y / tolerance);
  return `${qx}:${qy}`;
}

/**
 * Canonical key for a cycle: the lexicographically smallest rotation of
 * the ordered vertex keys, considering both directions. Used as a stable
 * identity so a rotated/reversed traversal of the same room reuses the
 * same auto-detected node across runs.
 */
export function canonicalizeCycleKeys(keys: string[]): string {
  if (keys.length === 0) return "";
  const rotations = (source: string[]): string[] => {
    const values: string[] = [];
    for (let i = 0; i < source.length; i++) {
      values.push([...source.slice(i), ...source.slice(0, i)].join(">"));
    }
    return values;
  };
  const candidates = [...rotations(keys), ...rotations([...keys].reverse())];
  candidates.sort();
  return candidates[0] ?? "";
}

export function polygonArea(points: Array<{ x: number; y: number }>): number {
  if (points.length < 3) return 0;
  let area = 0;
  for (let i = 0; i < points.length; i++) {
    const current = points[i]!;
    const next = points[(i + 1) % points.length]!;
    area += current.x * next.y - next.x * current.y;
  }
  return area / 2;
}

/**
 * Read an auto-detected signature out of a node's `properties` JSON, or
 * null if the node isn't flagged as auto-detected. Used to recognize which
 * rooms were generated by a previous auto-detect run so they can be
 * matched, updated, or pruned on the next run.
 */
export function getAutoDetectedSignature(node: FloorPlanNode): string | null {
  if (!node.properties) return null;
  try {
    const parsed = JSON.parse(node.properties) as Record<string, unknown>;
    if (parsed.autoDetected !== true) return null;
    const signature = parsed.boundarySignature;
    return typeof signature === "string" ? signature : null;
  } catch {
    return null;
  }
}

export function makeAutoDetectedProperties(signature: string, edgeIds: string[]): string {
  return JSON.stringify({
    autoDetected: true,
    boundarySignature: signature,
    sourceEdgeIds: edgeIds,
  });
}

type EndpointEntry = {
  sumX: number;
  sumY: number;
  count: number;
  neighbors: Set<string>;
  edgeIds: Set<string>;
};

function detectRegionsForEdges(
  edges: AutoDetectBoundaryEdge[]
): { regions: AutoDetectedRegion[]; hasBranching: boolean } {
  if (edges.length === 0) return { regions: [], hasBranching: false };

  const endpointByKey = new Map<string, EndpointEntry>();
  const edgeById = new Map<string, AutoDetectBoundaryEdge>();
  const edgeIdsByPair = new Map<string, string[]>();

  const addEndpoint = (key: string, x: number, y: number): void => {
    const existing = endpointByKey.get(key);
    if (existing) {
      existing.sumX += x;
      existing.sumY += y;
      existing.count += 1;
      return;
    }
    endpointByKey.set(key, {
      sumX: x,
      sumY: y,
      count: 1,
      neighbors: new Set<string>(),
      edgeIds: new Set<string>(),
    });
  };

  const pairKey = (a: string, b: string): string => (a < b ? `${a}|${b}` : `${b}|${a}`);
  const pickEdgeId = (a: string, b: string, allowed: Set<string>): string | null => {
    const ids = edgeIdsByPair.get(pairKey(a, b)) ?? [];
    for (const id of ids) {
      if (allowed.has(id)) return id;
    }
    return null;
  };
  const pointForKey = (key: string): { x: number; y: number } => {
    const entry = endpointByKey.get(key)!;
    return { x: entry.sumX / entry.count, y: entry.sumY / entry.count };
  };

  for (const edge of edges) {
    edgeById.set(edge.id, edge);
    addEndpoint(edge.startKey, edge.startX, edge.startY);
    addEndpoint(edge.endKey, edge.endX, edge.endY);
    endpointByKey.get(edge.startKey)!.neighbors.add(edge.endKey);
    endpointByKey.get(edge.endKey)!.neighbors.add(edge.startKey);
    endpointByKey.get(edge.startKey)!.edgeIds.add(edge.id);
    endpointByKey.get(edge.endKey)!.edgeIds.add(edge.id);
    const key = pairKey(edge.startKey, edge.endKey);
    const ids = edgeIdsByPair.get(key);
    if (ids) ids.push(edge.id);
    else edgeIdsByPair.set(key, [edge.id]);
  }

  const regions: AutoDetectedRegion[] = [];
  let hasBranching = false;
  const visitedKeys = new Set<string>();

  for (const startKey of endpointByKey.keys()) {
    if (visitedKeys.has(startKey)) continue;

    const queue = [startKey];
    visitedKeys.add(startKey);
    const componentKeys: string[] = [];
    const componentEdgeIds = new Set<string>();

    while (queue.length > 0) {
      const key = queue.shift()!;
      componentKeys.push(key);
      const endpoint = endpointByKey.get(key)!;
      for (const edgeId of endpoint.edgeIds) componentEdgeIds.add(edgeId);
      for (const neighbor of endpoint.neighbors) {
        if (visitedKeys.has(neighbor)) continue;
        visitedKeys.add(neighbor);
        queue.push(neighbor);
      }
    }

    if (componentKeys.length < 3 || componentEdgeIds.size < 3) continue;
    const componentKeySet = new Set(componentKeys);
    const isSimpleCycle = componentKeys.every((key) => {
      const endpoint = endpointByKey.get(key)!;
      let degree = 0;
      for (const neighbor of endpoint.neighbors) {
        if (componentKeySet.has(neighbor)) degree++;
      }
      if (degree > 2) hasBranching = true;
      return degree === 2;
    });
    if (!isSimpleCycle) continue;
    if (componentEdgeIds.size !== componentKeys.length) continue;

    const orderedKeys: string[] = [];
    const orderedEdgeIds: string[] = [];
    const firstKey = [...componentKeys].sort()[0]!;
    let currentKey = firstKey;
    let previousKey: string | null = null;
    let closed = false;

    // Track visited keys in an O(1) Set rather than an O(n) array scan.
    // The only legitimate revisit is returning to `firstKey` to close the
    // cycle — any other repeat means endpoint-tolerance quantization
    // merged a spurious near-vertex, so we abort that component rather
    // than silently emitting a region with a malformed signature.
    const cycleVisited = new Set<string>([firstKey]);

    for (let step = 0; step <= componentKeys.length; step++) {
      orderedKeys.push(currentKey);
      const endpoint = endpointByKey.get(currentKey)!;
      const neighbors = [...endpoint.neighbors].filter((neighbor) =>
        componentKeySet.has(neighbor)
      );
      const nextKey = neighbors.find((neighbor) => neighbor !== previousKey) ?? null;
      if (!nextKey) break;

      const edgeId = pickEdgeId(currentKey, nextKey, componentEdgeIds);
      if (edgeId) orderedEdgeIds.push(edgeId);

      if (nextKey === firstKey) {
        closed = orderedKeys.length === componentKeys.length;
        break;
      }
      if (cycleVisited.has(nextKey)) break;
      cycleVisited.add(nextKey);
      previousKey = currentKey;
      currentKey = nextKey;
    }

    if (!closed || orderedKeys.length < 3) continue;
    if (orderedEdgeIds.length !== orderedKeys.length) continue;

    const points = orderedKeys.map((key) => {
      const point = pointForKey(key);
      return { key, ...point };
    });
    const area = polygonArea(points.map((point) => ({ x: point.x, y: point.y })));
    if (Math.abs(area) < AUTO_DETECT_MIN_AREA) continue;

    let minX = Number.POSITIVE_INFINITY;
    let minY = Number.POSITIVE_INFINITY;
    let maxX = Number.NEGATIVE_INFINITY;
    let maxY = Number.NEGATIVE_INFINITY;
    for (const point of points) {
      minX = Math.min(minX, point.x);
      minY = Math.min(minY, point.y);
      maxX = Math.max(maxX, point.x);
      maxY = Math.max(maxY, point.y);
    }

    const width = maxX - minX;
    const height = maxY - minY;
    if (width < AUTO_DETECT_MIN_DIMENSION || height < AUTO_DETECT_MIN_DIMENSION) continue;

    const edgeTypes = orderedEdgeIds.map(
      (id) => edgeById.get(id)?.nodeType ?? ("wall" as const)
    );
    const nodeType: "room" | "zone" = edgeTypes.every((type) => type === "fence")
      ? "zone"
      : "room";
    const parentId = edges[0]?.parentId ?? null;
    const parentKey = toParentGroupKey(parentId);
    const signature = `${parentKey}|${nodeType}|${canonicalizeCycleKeys(orderedKeys)}`;

    regions.push({
      parentId,
      parentKey,
      nodeType,
      signature,
      edgeIds: orderedEdgeIds,
      minX,
      minY,
      width,
      height,
    });
  }

  return { regions, hasBranching };
}

/**
 * Entry point for the auto-detect pipeline. Groups wall/fence segments by
 * hierarchy parent, detects simple closed cycles per group, and returns
 * the full set of regions plus the parent keys that had branching walls
 * (used by the store to skip aggressive deletion in those parents).
 */
export function detectAutoDetectedRegions(
  wallLikeNodes: FloorPlanNode[],
  gridSize: number
): AutoDetectResult {
  const endpointTolerance = Math.max(
    1,
    gridSize * AUTO_DETECT_ENDPOINT_TOLERANCE_RATIO
  );
  const groupedEdges = new Map<string, AutoDetectBoundaryEdge[]>();

  for (const node of wallLikeNodes) {
    if (node.nodeType !== "wall" && node.nodeType !== "fence") continue;
    if (node.x2 === null || node.y2 === null) continue;
    const length = Math.hypot(
      (node.x2 ?? node.posX) - node.posX,
      (node.y2 ?? node.posY) - node.posY
    );
    if (length < 1) continue;

    const parentId = node.parentId ?? null;
    const parentKey = toParentGroupKey(parentId);
    const edge: AutoDetectBoundaryEdge = {
      id: node.id,
      nodeType: node.nodeType,
      parentId,
      startX: node.posX,
      startY: node.posY,
      endX: node.x2,
      endY: node.y2,
      startKey: toBoundaryPointKey(node.posX, node.posY, endpointTolerance),
      endKey: toBoundaryPointKey(node.x2, node.y2, endpointTolerance),
    };
    const grouped = groupedEdges.get(parentKey);
    if (grouped) grouped.push(edge);
    else groupedEdges.set(parentKey, [edge]);
  }

  const regions: AutoDetectedRegion[] = [];
  const blockedDeletionParentKeys = new Set<string>();
  const processedParentKeys = new Set<string>();
  for (const [parentKey, edges] of groupedEdges.entries()) {
    processedParentKeys.add(parentKey);
    const result = detectRegionsForEdges(edges);
    if (result.hasBranching) blockedDeletionParentKeys.add(parentKey);
    regions.push(...result.regions);
  }

  return { regions, blockedDeletionParentKeys, processedParentKeys };
}
